apiVersion: v1
kind: Secret
metadata:
  name: bmh-02
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh-02
  annotations:
    #inspect.metal3.io: disabled
spec:
  online: true
  bootMACAddress: 52:54:00:26:69:30
  # This particular hardware does not support UEFI so we use legacy
  bootMode: UEFI
  hardwareProfile: libvirt
  bmc:
    address: ipmi://192.168.122.1:6600
    credentialsName: bmh-02
    #disableCertificateVerification: true
    #  image:
    #checksumType: sha256
    #checksum: http://192.168.122.1/SHA256SUMS
    #format: qcow2
    #url: http://192.168.122.1/jammy-server-cloudimg-amd64.img
    #userData:
    #name: user-data
    #namespace: default
